### ISSUE TITLE
More escaping needed

### ISSUE THREAD

**Issue by jswetzen** [mmalecki/vim-node.js#2]
This did not work for me, I had to add more escape characters to the regex like this:
`^#.*\(\<node\>\|\<iojs\>\)`
I'm running VIM 7.4 on Ubuntu 15.10, but would this work for other versions of vim as well?

**Comment by mmalecki** [comment]
@jswetzen Thanks for the report! This was fixed by #3, in case you didn't get notified. Let me know if it doesn't work :)

**Comment by jswetzen** [comment]
Works like a charm, great! :)
